spring.application.name=gamehub

#informa onde está o banco
spring.datasource.url=jdbc:mysql://localhost/gamehub?createDatabaseIfNotExist=true

#Credenciais do banco
spring.datasource.username= SEU_USER_AQUI
spring.datasource.password= SUA_SENHA_AQUI

#O Hibernate cria/atualiza as tabelas de acordo com nossas classes @Entity.
spring.jpa.hibernate.ddl-auto=update
