spring.application.name=gamehub

#informa onde está o banco
spring.datasource.url=jdbc:mysql://localhost/gamehub?createDatabaseIfNotExist=true

#Credenciais do banco
spring.datasource.username=root
spring.datasource.password=password

#O Hibernate cria/atualiza as tabelas de acordo com nossas classes @Entity.
spring.jpa.hibernate.ddl-auto=update
